
package com.projetandoo.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Produtos", 
				  targetNamespace = "http://service.varejodigital.projetandoo/1.0/", 
				  wsdlLocation = "file:/home/fboaretto/Documentos/Projetandoo/WS/produtos.wsdl")
public class Produtos_Service extends Service
{

    private final static URL PRODUTOS_WSDL_LOCATION;
    private final static WebServiceException PRODUTOS_EXCEPTION;
    private final static QName PRODUTOS_QNAME = new QName("http://service.varejodigital.projetandoo/1.0/", "Produtos");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/fboaretto/Documentos/Projetandoo/WS/produtos.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PRODUTOS_WSDL_LOCATION = url;
        PRODUTOS_EXCEPTION = e;
    }

    public Produtos_Service() {
        super(__getWsdlLocation(), PRODUTOS_QNAME);
    }

    public Produtos_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), PRODUTOS_QNAME, features);
    }

    public Produtos_Service(URL wsdlLocation) {
        super(wsdlLocation, PRODUTOS_QNAME);
    }

    public Produtos_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PRODUTOS_QNAME, features);
    }

    public Produtos_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Produtos_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Produtos
     */
    @WebEndpoint(name = "ProdutosSOAP")
    public Produtos getProdutosSOAP() {
        return super.getPort(new QName("http://service.varejodigital.projetandoo/1.0/", "ProdutosSOAP"), Produtos.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy. 
     *     Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Produtos
     */
    @WebEndpoint(name = "ProdutosSOAP")
    public Produtos getProdutosSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.varejodigital.projetandoo/1.0/", "ProdutosSOAP"), Produtos.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PRODUTOS_EXCEPTION != null) {
            throw PRODUTOS_EXCEPTION;
        }
        return PRODUTOS_WSDL_LOCATION;
    }

}
